name: GitHub Actions Demo
on: 
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build application
        run: dotnet build
      - name: Run tests
        run: dotnet test ./UnitTests
      - name: Install formatter
        run: dotnet tool install -g dotnet-format
      - name: Format solution
        run: dotnet format --check